NVIDIA/spark-rapids-examples

examples/aggregator/pom.xml
Maven shade plugin to aggregate sample app jars(utils/taxi/mortgage/agaricus) into the `sample_xgboost_apps-${project.version}.jar`
=> To build the aggregator jar

README.md, examples/pca/README.md
Update documents for upcoming 21.10 release. 
related to: https://github.com/NVIDIA/spark-rapids-ml/issues/8
Note, the jar links are not available until jars are officially released. 
Better to merge after release.
=> Update PCA related docs

README.md, hadoop/device-plugins/gpu-mig/README.md, hadoop/device-plugins/gpu-mig/pom.xml, hadoop/device-plugins/gpu-mig/scripts/getMIGGPUs, hadoop/device-plugins/gpu-mig/src/main/java/com/nvidia/spark/NvidiaGPUMigPluginForRuntimeV2.java, hadoop/device-plugins/gpu-mig/src/test/java/com/nvidia/spark/TestNvidiaGPUMigPluginForRuntimeV2.java
This plugin works with YARN 3.3.0+ and adds in support for GPUs with MIG capabilities. 
Documentation tying it together with the Spark Rapids Plugin  will come later in the spark rapids repo.  
The documentation included should cover the details and if something isn't clear please let me know as I should enhance.
Tested manually on node with multiple A100's using YARN 3.3.1 using cgroups and docker.  
The plugin code was originally from Hadoop and modified to add MIG support. I also removed topology related scheduling code since we expect only 1 GPU per executor.  we use nvidia-smi -L to get the MIG information and parse that output.
=> Add YARN Device Plugin to support MIG GPUs

examples/pca/main.scala
This failed in our CI test due to OOM, so reduce rows. The speedup number can also be guaranteed in this case.
=> Reduce rows to fit lower memory test environment

examples/MIG-Support/yarn-unpatched/README.md, examples/MIG-Support/yarn-unpatched/scripts/mig2gpu.sh, examples/MIG-Support/yarn-unpatched/scripts/nvidia-container-cli-wrapper.sh
- This script fails to reset migEnabled variable
such that it is ignored even if ENABLE_NON_MIG_GPUS=1
- Get rid of redundant line counter leading to occasional off-by-1 errors.
We rely on the internal size tracking of the bash input line array.
Verify with 
```bash
MIG_AS_GPU_ENABLED=1 ENABLE_NON_MIG_GPUS=1 ./examples/MIG-Support/yarn-unpatched/scripts/nvidia-smi-wrapper.sh -q -x | xmllint --format -
```
Before the fix providing a list of GPU indices to the wrapper would fail the docker container launch with `unknown device: unknown.`
after the fix:
```
docker run --rm --gpus '"device=0"' --runtime nvidia nvidia/cuda:11.5.1-devel-ubuntu20.04 nvidia-smi -L
GPU 0: NVIDIA A30 (UUID: GPU-05aa99be-b706-0dc1-ab62-dd12f2227b7d)
MIG 1c.2g.12gb  Device  0: (UUID: …
```
=> Fix non-MIG GPU output ignored

examples/MIG-Support/yarn-unpatched/README.md, examples/MIG-Support/yarn-unpatched/scripts/nvidia-container-cli-wrapper.sh, examples/MIG-Support/yarn-unpatched/scripts/nvidia-smi
While testing on centos 7 CDP cluster, I found that the nvidia-container-cli-wrapper.sh script was not properly passing on the mig device.  Debugging it I found that when it reads the output from the mig2gpu.sh and redirect into the while read line, all the output got concatenated onto a single line.  The while loop expects it to be separate lines.  I was able to fix it by changing the redirect. tested on both centos and ubuntu.
Also update the docs to include the requirement for driver version 470+ because I ran into an issue with 450 where the output of nvidia-smi was different.
I also found a YARN change that could affect the naming of the script so documented that.
=> Fix read of mig2gpu.sh on centos 7 and update docs 

examples/Spark-cuML/pca/Dockerfile
To fix https://github.com/NVIDIA/spark-rapids-examples/issues/98.
- use main branch for spark-rapids-ml to download release jars.
- change cuDF package version.
=> Fix PCA example docker build failure

examples/MIG-Support/yarn-unpatched/README.md, examples/MIG-Support/yarn-unpatched/scripts/nvidia-container-cli-wrapper.sh, examples/MIG-Support/yarn-unpatched/scripts/nvidia-smi
Change for branch 22.02 of PR https://github.com/NVIDIA/spark-rapids-examples/pull/114
While testing on centos 7 CDP cluster, I found that the nvidia-container-cli-wrapper.sh script was not properly passing on the mig device. Debugging it I found that when it reads the output from the mig2gpu.sh and redirect into the while read line, all the output got concatenated onto a single line. The while loop expects it to be separate lines. I was able to fix it by changing the redirect. tested on both centos and ubuntu.
Also update the docs to include the requirement for driver version 470+ because I ran into an issue with 450 where the output of nvidia-smi was different.
I also found a YARN change that could affect the naming of the script so documented that.
Signed-off-by: Thomas Graves …
=> Fix read of mig2gpu.sh on centos 7 and update docs

README.md
Use the folder link for the guide in README
So it jumps into the folder which shows code and README
Signed-off-by: gashen <gashen@nvidia.com>
=> Add spark-cuspatial to main README

examples/Spark-cuSpatial/Dockerfile, examples/Spark-cuSpatial/Dockerfile.awsdb, examples/Spark-cuSpatial/README.md, examples/Spark-cuSpatial/src/main/native/src/PointInPolygonJni.cpp
Fix https://github.com/NVIDIA/spark-rapids-examples/issues/128
Change the code to match cuDF 22.04 API. 
cuDF 22.04 changed the parameter type to "reduce_aggregation" instead of "aggregation".
With this change, it can not be built with cuDF 22.02.
We'll update the README later.
=> Move to cuspatial 22.04

examples/MIG-Support/device-plugins/gpu-mig/README.md, examples/MIG-Support/resource-types/gpu-mig/README.md, examples/MIG-Support/yarn-unpatched/README.md
YARN doesn't need cgroups when Docker is used. isolation is through the nvidia docker v2 plugin.
Signed-off-by: Thomas Graves <tgraves@nvidia.com>
=> Clarify mig documentation to remove cgroup references

examples/Spark-cuSpatial/src/main/java/com/nvidia/spark/rapids/udf/PointInPolygon.java
Change the UDF input type to Double to align with the type of the example dataset.
Signed-off-by: Liangcai Li <liangcail@nvidia.com>
=> cuSpatial: Use Double as the input type

examples/XGBoost-Examples/agaricus/pom.xml, examples/XGBoost-Examples/aggregator/pom.xml, examples/XGBoost-Examples/mortgage/pom.xml, examples/XGBoost-Examples/pom.xml, examples/XGBoost-Examples/taxi/pom.xml, examples/XGBoost-Examples/utility/pom.xml
Need to upgrade Sample app's version to 0.2.3-SNAPSHOT instead of overwriting the 0.2.2
As the 0.2.2 sample app jar is used for nvidia/xgboost v1.4.2 and berfore versions supporting pyspark/CV tests
=> upgrade Sample app's version

examples/XGBoost-Examples/mortgage/notebooks/python/cv-mortgage-gpu.ipynb, examples/XGBoost-Examples/mortgage/notebooks/python/mortgage-gpu.ipynb, examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-ETL.ipynb, examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-gpu.ipynb, examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage_gpu_crossvalidation.ipynb
Follow up https://github.com/NVIDIA/spark-rapids-examples/pull/203
Keep the paths of Mortgage consistent in ETL and its downstream jobs
Add an variable to save ETL output to local.
=> Keep the paths of Mortgage consistent in ETL and its downstream jobs

examples/UDF-Examples/RAPIDS-accelerated-UDFs/Dockerfile, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
fix issue 
```
15:34:07  [INFO]      [exec] CMake Error at /home/jenkins/agent/workspace/jenkins-examples-udf-examples-native-40/examples/UDF-Examples/RAPIDS-accelerated-UDFs/target/cpp-build/_deps/rapids-cmake-src/CMakeLists.txt:28 (cmake_minimum_required):
15:34:07  [INFO]      [exec]   CMake 3.23.1 or higher is required.  You are running version 3.20.5
```
in udf example build
cudf has updated their cmake requirement to 3.23.1+, the change has been verified in CI
=> Update default cmake to 3.23.X in udf exmaple dockerfile

examples/XGBoost-Examples/utility/scala/src/com/nvidia/spark/examples/utility/XGBoostArgs.scala
Args defined in the Map 'supportedArgs' is parsed as app/spark, not passing to XGBoost.
Remove 'rabitTrackerHost' from 'supportedArgs' Map, so that this arg can be PASS to XGBoost.
Fix issue: https://github.com/NVIDIA/spark-rapids-examples/issues/242
=> Pass 'rabitTrackerHost' as XGBoost arg

.github/workflows/auto-merge.yml
auto-merge triggered by github actions on `branch-22.12` to create a PR keeping `branch-23.02` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-22.12 to branch-23.02 [skip ci] [bot]

examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/python/asserts.py, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/python/spark_init_internal.py
Closes #268
`com.nvidia.spark.rapids.ExecutionPlanCaptureCallback` is renamed to `org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback` on Spark-Rapids repo branch 23.02
Should update the package accordingly.
Signed-off-by: Chong Gao <res_life@163.com>
=> Fix UDF test cases failed on Databricks 3.1.2

examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/hive/DecimalFraction.java, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/hive/StringWordCount.java, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/hive/URLDecode.java, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/hive/URLEncode.java, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/java/CosineSimilarity.java, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/java/DecimalFraction.java, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/java/URLDecode.java, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/java/URLEncode.java, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/scala/com/nvidia/spark/rapids/udf/scala/URLDecode.scala, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/scala/com/nvidia/spark/rapids/udf/scala/URLEncode.scala, examples/UDF-Examples/Spark-cuSpatial/src/main/java/com/nvidia/spark/rapids/udf/PointInPolygon.java
RapidsUDF.evaluateColumnar has a new parameter of numRows
Close https://github.com/NVIDIA/spark-rapids-examples/issues/258
Depend on https://github.com/NVIDIA/spark-rapids/pull/7377
Signed-off-by: Gary Shen <gashen@nvidia.com>
=> Change the new interface of RapidsUDF

.github/workflows/auto-merge.yml
auto-merge triggered by github actions on `branch-23.02` to create a PR keeping `branch-23.04` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-23.02 to branch-23.04 [skip ci] [bot]

.github/workflows/auto-merge.yml
auto-merge triggered by github actions on `branch-23.04` to create a PR keeping `branch-23.06` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-23.04 to branch-23.06 [skip ci] [bot]

examples/XGBoost-Examples/pom.xml
xgboost 1.7.x doesn't update the kryo to the latest, which may have vulnerability issues. xgboost 2.0.0-snapshot has fixed it, so this PR update xgb dep to the 2.0.0-snapshot.
=> update xgboost dependency to the latest

dockerfile/Dockerfile, examples/ML+DL-Examples/Spark-cuML/pca/Dockerfile, examples/UDF-Examples/RAPIDS-accelerated-UDFs/Dockerfile
Update cuda docker images as some CUDA versioned container images will be DELETED from DOCKER HUB.
**The tags for the following CUDA versioned container images will be DELETED from NGC AND DOCKER HUB**
* 11\.7.0
* 11\.6.1
* 11\.6.0
* 11\.5.1
* 11\.5.0
* 11\.4.2
* 11\.4.1
* 11\.4.0
* 11\.3.0
* 11\.2.1
* 11\.2.0
* 10\.2
* 10\.1
* 10\.0
* 9\.2
* 9\.1
* 9\.0
* 8\.0
* 7\.0
=> Update cuda docker images

examples/ML+DL-Examples/Spark-cuML/pca/Dockerfile, examples/ML+DL-Examples/Spark-cuML/pca/README.md, examples/ML+DL-Examples/Spark-cuML/pca/pom.xml, examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
Note that the last rapids-4-spark-ml release version is 22.02.0, snapshot version is 23.04.0-SNPASHOT,
and this demo could only work with v22.02.0 spark-ml version, and only compatible with spark-rapids versions prior to 23.08.1 .
=> update PCA demo to a fix spark-rapids plugin version

examples/UDF-Examples/RAPIDS-accelerated-UDFs/README.md, examples/UDF-Examples/RAPIDS-accelerated-UDFs/run_pyspark_from_build.sh, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/src/CosineSimilarityJni.cpp, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/java/CosineSimilarity.java
auto-merge triggered by github actions on `branch-23.10` to create a PR keeping `branch-23.12` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-23.10 to branch-23.12 [skip ci] [bot]

.github/workflows/auto-merge.yml
auto-merge triggered by github actions on `branch-23.12` to create a PR keeping `branch-24.02` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-23.12 to branch-24.02 [skip ci] [bot]

examples/UDF-Examples/RAPIDS-accelerated-UDFs/README.md, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
Fixes #344.  Verified by running `ldd` on the resulting build artifact and verifying there's no longer a dependency on libcudart, as well as running the native UDF test to verify UDFs still work with the static runtime.  Also updated the native UDF test example to show more useful examples and output.
=> Update RAPIDS accelerated native UDFs example to use static CUDA runtime

examples/UDF-Examples/RAPIDS-accelerated-UDFs/Dockerfile, examples/UDF-Examples/RAPIDS-accelerated-UDFs/README.md
Install ccache in Dockerfile used to build UDF example.
Update README to explain how to use it by adding some environment variables
close https://github.com/NVIDIA/spark-rapids-examples/issues/343
=> Enable ccache in UDF examples build

.github/workflows/auto-merge.yml
auto-merge triggered by github actions on `branch-24.02` to create a PR keeping `branch-24.04` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-24.02 to branch-24.04 [skip ci] [bot]

examples/UDF-Examples/RAPIDS-accelerated-UDFs/README.md, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
This reverts #347 which should have targeted branch-24.02 instead of main.
=> Revert CUDA static runtime change from main

examples/ML+DL-Examples/Spark-cuML/pca/pom.xml, examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh, examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt, examples/UDF-Examples/Spark-cuSpatial/pom.xml
1, update rapidsai cudf/rmm to branch-24.04, to fix:
issue: https://github.com/NVIDIA/spark-rapids-examples/issues/349
2, Chnage Spark-cuML and rapids-UDF exmaple apps' version to 24.04.0-SNAPSHOT
3, Fix typo in Spark-cuSpatial
=> rapids examples's version to 24.04.0-SNAPSHOT

examples/XGBoost-Examples/agaricus/pom.xml, examples/XGBoost-Examples/aggregator/pom.xml, examples/XGBoost-Examples/assembly/assembly-no-scala.xml, examples/XGBoost-Examples/mortgage/pom.xml, examples/XGBoost-Examples/pom.xml, examples/XGBoost-Examples/taxi/pom.xml, examples/XGBoost-Examples/utility/pom.xml
This PR adds scala version for the artifactId to distinguish the scala 2.12 and scala 2.13.
To compile xgboost samples against scala 2.13, you can use below command
``` bash
mvn clean package -P scala-2.13
```
=> Support scala 2.13 for xgboost samples

examples/ML+DL-Examples/Spark-cuML/pca/pom.xml, examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml, examples/UDF-Examples/Spark-cuSpatial/pom.xml
Init project version 24.04.0-SNAPSHOT
Signed-off-by: Tim Liu [timl@nvidia.com](mailto:timl@nvidia.com)
=> Init project version 24.04.0-SNAPSHOT

.github/workflows/auto-merge.yml, .github/workflows/signoff-check.yml
auto-merge triggered by github actions on `branch-24.04` to create a PR keeping `branch-24.06` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-24.04 to branch-24.06 [skip ci] [bot]

examples/XGBoost-Examples/agaricus/notebooks/python/agaricus-gpu.ipynb, examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb, examples/XGBoost-Examples/mortgage/notebooks/python/cv-mortgage-gpu.ipynb, examples/XGBoost-Examples/mortgage/notebooks/python/mortgage-gpu.ipynb, examples/XGBoost-Examples/taxi/notebooks/python/cv-taxi-gpu.ipynb, examples/XGBoost-Examples/taxi/notebooks/python/taxi-gpu.ipynb
After installing latest Jupyter notebooke, the json format check is strick, due to passing a string value "true"
for the "use_gpu":"true", "use_gpu": True is required.
```
params = {
"tree_method": "gpu_hist",
"grow_policy": "depthwise",
"num_workers": 1,
"use_gpu": "true", -->  "device": "cuda"
}
```
TypeError: Invalid param value given for param "use_gpu".
Boolean Param requires value of type bool. Found <class 'str'>.
More over, "use_gpu": True is deprecated in dmlc/XGBoost, change to user "device": "cuda" instead
=> Fix invalid param value "use_gpu":"true"

.github/workflows/auto-merge.yml
auto-merge triggered by github actions on `branch-24.06` to create a PR keeping `branch-24.08` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-24.06 to branch-24.08 [skip ci] [bot]

tools/databricks/README.md
This PR updates the README section for Databricks notebooks about the S3 event log support.
=> [DOC] Update Databricks Notebooks README for S3 event log support

examples/UDF-Examples/RAPIDS-accelerated-UDFs/Dockerfile, examples/UDF-Examples/RAPIDS-accelerated-UDFs/README.md
Fixes #389, relates to #362.  The C++ compiler in the RAPIDS accelerated Dockerfile is too old for recent libcudf code.  This fixes the RAPIDS accelerated native UDF build by updating the Dockerfile to more closely match the build environment from spark-rapids-jni, fixing the main issue reported in #362.
Leaving #362 open, since we really should update the build to use the same Dockerfile so it keeps in sync even when spark-rapids-jni updates.
=> Update RAPIDS accelerated UDF Dockerfile to better match spark-rapids-jni

tools/databricks/README.md, tools/databricks/[RAPIDS Accelerator for Apache Spark] Profiling Tool Notebook Template.ipynb, tools/databricks/[RAPIDS Accelerator for Apache Spark] Qualification Tool Notebook Template.ipynb
Fixes #425. This PR updates the Databricks Notebook for Tools v24.08.0.
- Updated `TOOLS_VER` to `24.08.0`
- Included a cell to show the status of each eventlog file that was provided
-  Included a cell to show the metadata of each app containing the following info:
- Recommended GPU cluster
- File location of full cluster config recommendations
- File location of only Gpu specific config recommendation
- Updated `TOOLS_VER` to `24.08.0`
=> Update Databricks Notebook for Tools v24.08.0

tools/databricks/README.md, tools/databricks/[RAPIDS Accelerator for Apache Spark] Profiling Tool Notebook Template.ipynb, tools/databricks/[RAPIDS Accelerator for Apache Spark] Qualification Tool Notebook Template.ipynb
auto-merge triggered by github actions on `branch-24.08` to create a PR keeping `branch-24.10` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-24.08 to branch-24.10 [skip ci] [bot]

examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
```
15:42:45  [INFO]      [exec] -- Configuring incomplete, errors occurred!
15:42:45  [INFO]      [exec] CMake Error at /usr/local/cmake-3.26.4-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
15:42:45  [INFO]      [exec]   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
15:42:45  [INFO]      [exec]   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
15:42:45  [INFO]      [exec]   OPENSSL_INCLUDE_DIR)
15:42:45  [INFO]      [exec] Call Stack (most recent call first):
15:42:45  [INFO]      [exec]   /usr/local/cmake-3.26.4-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
15:42:45  [INFO]      [exec] …
```
=> Disable kvikio remote I/O to avoid openssl dependencies in cudf build

examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/conditional_generation_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/conditional_generation_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/pipelines_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/pipelines_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/sentence_transformers_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/pytorch/image_classification_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/pytorch/regression_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/feature_columns_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/image_classification_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/keras-metadata_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/text_classification_tf.ipynb
After discussing with @YanxuanLiu @eordentlich, we are skipping the Triton portions of the DL notebooks for now, allowing us to run the notebooks in Docker on the pipeline (in conjunction with [this PR](https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/merge_requests/1821#note_25809163)). 
Added "TRITON" cell tags to all Triton-related cells to enable using Jupyter TagPreprocessor to detect and skip Triton cells without modifying any code on the user-end. 
Triton cells can be re-enabled when we have either safe Docker-in-Docker execution or we refactor to use PyTriton client (in progress). 
Avoiding use of relative paths for datasets to address CI failures in [text_classification_tf](https://prod.blsm.nvidia.com/sw-gpu-spark-jenkins/blue/organizations/jenkins/yanxuan_ml-notebook/d …
=> Add tags to skip Triton cells for CI/CD

examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
1. Updated the dataset path
2. Save step durations into result file.
=> Run micro-benchmark on GCP

examples/UDF-Examples/RAPIDS-accelerated-UDFs/Dockerfile, examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
To port the cmake update for JNI from cudf side
This has been verified internally, passed both build and test cases
```
[exec] -- Building using CMake version: 3.28.6
```
=> Update udf native example cmake version to 3.28.6

tools/emr/README.md, tools/emr/[RAPIDS Accelerator for Apache Spark] Profiling Tool Notebook Template.ipynb, tools/emr/[RAPIDS Accelerator for Apache Spark] Qualification Tool Notebook Template.ipynb
* Add Tools Notebooks for EMR
* Update README
* Sign-off commit
---------
=> special cherry pick for re:invent in main branch

.github/workflows/add-to-project.yml
follow up of https://github.com/NVIDIA/spark-rapids-common/issues/22
to avoid update action details for multiple `spark-rapids*` repos in the future
=> Use common add to project [skip ci]

examples/ML+DL-Examples/Spark-DL/dl_inference/README.md, examples/ML+DL-Examples/Spark-DL/dl_inference/databricks/setup/init_spark_dl.sh, examples/ML+DL-Examples/Spark-DL/dl_inference/dataproc/setup/start_cluster.sh, examples/ML+DL-Examples/Spark-DL/dl_inference/requirements.txt, examples/ML+DL-Examples/Spark-DL/dl_inference/torch_requirements.txt
Pin torch<=2.5.1 until torch-tensorrt has a compatible version for torch 2.6.
Add troubleshooting to update libstdc++ for Triton server binary requirements; can occur if default conda channel is used and not up to date.
Removed ipykernel from requirements since it's already pulled in by jupyterlab (and slows pip down a lot).
=> Fix torch-tensorrt install, libstdc++ troubleshooting

examples/ML+DL-Examples/Spark-DL/dl_inference/README.md, examples/ML+DL-Examples/Spark-DL/dl_inference/dataproc/setup/init_spark_dl.sh, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/conditional_generation_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/conditional_generation_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/pipelines_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/pipelines_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/sentence_transformers_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/pytorch/housing_regression_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/pytorch/image_classification_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/pytriton_utils.py, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/image_classification_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/keras_preprocessing_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/keras_resnet50_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/text_classification_tf.ipynb
Consolidate util functions into a server manager class to simplify usage. (Note that notebooks were rerun but only the Triton utility invocations are changed). 
Also on Dataproc, the utils file needs to be copied driver root dir instead of the same directory as the notebooks, since sc.addPyFile on Dataproc only accepts absolute paths from root.
=> Implement and use TritonServerManager class

examples/ML+DL-Examples/Spark-DL/dl_inference/README.md, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/qwen-2.5-7b_torch.ipynb
Adding Qwen notebook, mainly to demonstrate how to leverage system prompts/chat templates for batch inference. Also serves as a non-gated and faster alternative to Gemma.
=> Add Qwen-2.5 Notebook

examples/ML+DL-Examples/Spark-DL/dl_inference/README.md, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/qwen-2.5-7b_torch.ipynb
auto-merge triggered by github actions on `branch-25.02` to create a PR keeping `branch-25.04` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
=> [auto-merge] branch-25.02 to branch-25.04 [skip ci] [bot]

examples/ML+DL-Examples/Spark-DL/dl_inference/README.md, examples/ML+DL-Examples/Spark-DL/dl_inference/databricks/README.md, examples/ML+DL-Examples/Spark-DL/dl_inference/databricks/setup/init_spark_dl.sh, examples/ML+DL-Examples/Spark-DL/dl_inference/databricks/setup/start_cluster.sh, examples/ML+DL-Examples/Spark-DL/dl_inference/dataproc/README.md, examples/ML+DL-Examples/Spark-DL/dl_inference/dataproc/setup/start_cluster.sh, examples/ML+DL-Examples/Spark-DL/dl_inference/requirements.txt
- Pin of urllib3<2 was an artifact from the old Databricks runtime we were using and is no longer needed. Unpinning allows the latest pytriton to be used. 
- Install libstdcxx by default since latest PyTriton requires 3.4.30
- While testing on CSPs, cleaned up/fixed some instructions.
=> Update urllib3 requirement and cleanup instructions

examples/ML+DL-Examples/Spark-DL/dl_inference/databricks/README.md, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/deepseek-r1_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/gemma-7b_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/qwen-2.5-7b_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/pytriton_utils.py
Relying on Huggingface cache to load LLMs is finicky on DBFS and when an access token is needed. Switch to downloading the model and using the abs path, which is better practice anyway. 
Added barrier to pytriton server startup to ensure all servers are shut down if one fails.
=> Use absolute paths instead of relying on HF cache

examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/conditional_generation_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/conditional_generation_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/deepseek-r1_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/gemma-7b_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/pipelines_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/pipelines_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/qwen-2.5-7b_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/sentence_transformers_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/pytorch/housing_regression_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/pytorch/image_classification_torch.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/pytriton_utils.py, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/image_classification_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/keras_preprocessing_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/keras_resnet50_tf.ipynb, examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/text_classification_tf.ipynb
Infer number of executors, providing "num_nodes" is no longer needed.
Avoid hardcoding 1 GPU per exec to prepare for tensor-parallel examples.
=> Infer number of executors / executor resources for PyTriton

tools/databricks/[RAPIDS Accelerator for Apache Spark] Profiling Tool Notebook Template.ipynb, tools/databricks/[RAPIDS Accelerator for Apache Spark] Qualification Tool Notebook Template.ipynb
Fixes #517 
We need to improve our Databricks Qualification and Profiling Quick Start Notebooks to support programmatic specification of the Tools Version. This is a prerequisite for automating Tools Versions used in these notebooks.
1. Tools Version from Databricks API:
2. Tools Version used in the Notebook:
=> Adding Programmatic Tools Version Configuration to Databricks Notebooks

examples/ML+DL-Examples/Spark-DL/dl_inference/server_utils.py, examples/ML+DL-Examples/Spark-DL/dl_inference/vllm/qwen-2.5-7b_vllm.ipynb
Follows [vLLM #6554 comment](https://github.com/vllm-project/vllm/issues/6544#issuecomment-2237994380) to properly release vLLM model from GPU memory.
(Particularly, vLLM now wraps/releases the torch process group, so the old code was raising an assertion error).
=> Fix unloading of vLLM model from GPU

examples/UDF-Examples/RAPIDS-accelerated-UDFs/Dockerfile
rapids build now requires at least 3.30.4 (the same as JNI)
=> Update Dockerfile to use cmake 3.30.4

examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
closes #535
`https://github.com/rapidsai/rapids-cmake/blob/branch-25.06/RAPIDS.cmake` changed, it requires: rapids_cmake_version.
Just set the version.
For Every release, we MUST manually update the version of rapids_cmake_version.
Signed-off-by: Chong Gao <res_life@163.com>
=> Fix no rapids cmake version
