- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflow/signoff-check.yml
- .github/workflow/signoff-check/Dockerfile
- .github/workflow/signoff-check/action.yml
- .github/workflow/signoff-check/signoff-check
Signed-off-by: Yuan Li <yuali@yuali-mlt.client.nvidia.com>
add signoff checks
> add signoff checks

- .github/workflow/signoff-check.yml
- docs/get-started/xgboost-examples/building-sample-apps/python.md
- docs/get-started/xgboost-examples/building-sample-apps/scala.md
- docs/get-started/xgboost-examples/csp/databricks/init-notebook-for-rapids-spark-xgboost-on-databricks-gpu-7.0-ml.ipynb
- docs/get-started/xgboost-examples/on-prem-cluster/kubernetes.md
Signed-off-by: Yuan Li <yuali@yuali-mlt.client.nvidia.com>
fix error path names
fix #7
> fix error path names

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflow/signoff-check.yml
- .github/workflow/signoff-check/Dockerfile
- .github/workflow/signoff-check/action.yml
- .github/workflow/signoff-check/signoff-check
- docs/get-started/xgboost-examples/building-sample-apps/python.md
- docs/get-started/xgboost-examples/building-sample-apps/scala.md
- docs/get-started/xgboost-examples/csp/databricks/init-notebook-for-rapids-spark-xgboost-on-databricks-gpu-7.0-ml.ipynb
- docs/get-started/xgboost-examples/on-prem-cluster/kubernetes.md
Signed-off-by: Yuan Li <yuali@yuali-mlt.client.nvidia.com>
fix error paths and add signoff checks
> fix error paths and add signoff checks

- docs/get-started/xgboost-examples/notebook/toree.md
To fix https://github.com/NVIDIA/spark-rapids-examples/issues/22
> Update Toree installation doc

- examples/pca/Dockerfile
- examples/pca/PCA example notebook.ipynb
- examples/pca/README.md
- examples/pca/main.scala
- examples/pca/pom.xml
- examples/pca/scala/src/com/nvidia/spark/examples/pca/Main.scala
- examples/pca/spark-env.sh
- examples/pca/spark-submit.sh
- examples/pca/start-spark.sh
- add README
- add example scala code for spark-shell
- add notebook for quick demo
- add dockerfile for quick test
- add example app scala code for spark-submit
> Add spark-rapids-ml PCA algo example

- datasets/preparing_datasets.md
- docs/get-started/xgboost-examples/prepare-package-data/preparation-python.md
- docs/get-started/xgboost-examples/prepare-package-data/preparation-scala.md
- examples/mortgage/notebooks/python/MortgageETL.ipynb
update mortgage dataset download links
> update mortgage dataset download links

- examples/pca/Dockerfile
- examples/pca/main.scala
- examples/pca/scala/src/com/nvidia/spark/examples/pca/Main.scala
- examples/pca/spark-submit.sh
Update environment setup due to https://github.com/NVIDIA/spark-rapids-ml/pull/19
> Update Dockerfile and API for transform PR

- examples/pca/main.scala
- set the correct input column for the CPU case.
> Fix a bug for cpu PCA case

- examples/pca/README.md
- examples/pca/pom.xml
- examples/pca/spark-submit.sh
> Update PCA jar's version to 21.12.0-SNAPSHOT

- examples/pca/scala/src/com/nvidia/spark/examples/pca/Main.scala
> Fix inpu col for CPU

- examples/Spark-cuML/pca/main.scala
> fix broken code in main file

- examples/Spark-ETL+XGBoost/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
ETL + XGBoost Train & Transform
Signed-off-by: gashen <gashen@nvidia.com>
> Add End2end notebook of mortgage

- examples/Spark-cuML/pca/pom.xml
> Change PCAExample jar's version to 22.02.0-SNAPSHOT

- examples/Spark-ETL+XGBoost/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
Rename the variable trans_data to test_data
Add spark.conf to support reading CSV on GPU
Remove some XGBoost parameters, use default value
Signed-off-by: gashen <gashen@nvidia.com>
> Remove the step of CSV to Parquet

- examples/Spark-cuML/pca/scala/src/com/nvidia/spark/examples/pca/Main.scala
> Fix input col

- examples/Spark-cuML/pca/scala/src/com/nvidia/spark/examples/pca/Main.scala
To fix https://github.com/NVIDIA/spark-rapids-examples/issues/85
> Add mean center before pca

- examples/Spark-cuML/pca/scala/src/com/nvidia/spark/examples/pca/Main.scala
> Reduce data size to run in test environment

- .github/workflows/auto-merge.yml
- .github/workflows/auto-merge/Dockerfile
- .github/workflows/auto-merge/action.yml
- .github/workflows/auto-merge/automerge
add auto-merge github action and enabled auto-merge from branch-22.02 to branch-22.04
> Enable auto-merge

- .github/workflows/auto-merge.yml
- .github/workflows/auto-merge/Dockerfile
- .github/workflows/auto-merge/action.yml
- .github/workflows/auto-merge/automerge
auto-merge triggered by github actions on `branch-22.02` to create a PR keeping `branch-22.04` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-22.02 to branch-22.04 [skip ci] [bot]

- README.md
- examples/MIG-Support/README.md
- examples/MIG-Support/yarn-unpatched/README.md
Explain why the user observes GPU index 0 for all executors
Signed-off-by: Gera Shegalov <gera@apache.org>
> Add language clarifying GPU address in Spark on YARN with  isolation

- examples/MIG-Support/README.md
Signed-off-by: Gera Shegalov <gera@apache.org>
> Remove link-breaking newline in MIG-Support/README

- examples/RAPIDS-accelerated-UDFs/README.md
update cudf jni doc from legacy to stable
> update cudf jni doc from legacy to stable

- examples/Spark-cuML/pca/pom.xml
- examples/Spark-cuML/pca/spark-submit.sh
> Change PCAExample version to 22.04.0-SNAPSHOT

- examples/Spark-cuML/pca/Spark_PCA_End_to_End.ipynb
- examples/Spark-cuML/pca/scala/src/com/nvidia/spark/examples/pca/Main.scala
> add overwrite mode when saving generated dummy data for PCA test

- examples/RAPIDS-accelerated-UDFs/README.md
- examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/Spark-cuML/pca/README.md
> Update for the cudf/rapids v22.02.0 release

- .github/workflows/auto-merge.yml
created branch-22.06, enable auto-merge
> Enable auto-merge from branch-22.04 to branch-22.06

- examples/Spark-cuSpatial/README.md
> update cuspatial build doc

- examples/Spark-cuSpatial/README.md
auto-merge triggered by github actions on `branch-22.04` to create a PR keeping `branch-22.06` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-22.04 to branch-22.06 [skip ci] [bot]

- examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
- examples/Spark-cuML/pca/Dockerfile
- examples/Spark-cuML/pca/pom.xml
- examples/Spark-cuML/pca/spark-submit.sh
- examples/Spark-cuSpatial/Dockerfile
- examples/Spark-cuSpatial/Dockerfile.awsdb
- examples/Spark-cuSpatial/README.md
- examples/Spark-cuSpatial/gpu-run.sh
- examples/Spark-cuSpatial/notebooks/spatial_join_standalone.ipynb
- examples/Spark-cuSpatial/pom.xml
- examples/Spark-cuSpatial/src/main/native/CMakeLists.txt
example folder only for nightly build. Doc update should wait untill new release is out.
verified example build internally
> Init 22.06.0-SNAPSHOT

- examples/XGBoost-Examples/README.md
> fix broken links in repo

- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage_gpu_crossvalidation.ipynb
- examples/XGBoost-Examples/taxi/notebooks/scala/taxi_gpu_crossvalidation.ipynb
> Run mortgage/taxi crossvalidation tests using spark CrossValidator

- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage_gpu_crossvalidation.ipynb
- examples/XGBoost-Examples/taxi/notebooks/scala/taxi_gpu_crossvalidation.ipynb
auto-merge triggered by github actions on `branch-22.06` to create a PR keeping `branch-22.08` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-22.06 to branch-22.08 [skip ci] [bot]

- examples/XGBoost-Examples/utility/scala/src/com/nvidia/spark/examples/utility/XGBoostArgs.scala
Signed-off-by: Suraj Aralihalli <suraj.ara16@gmail.com>
> initial commit: fix print statement error in XGBoostArgs.scala

- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/Spark-cuSpatial/Dockerfile
- examples/UDF-Examples/Spark-cuSpatial/README.md
- examples/UDF-Examples/Spark-cuSpatial/gpu-run.sh
- examples/UDF-Examples/Spark-cuSpatial/notebooks/cuspatial_sample_standalone.ipynb
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
> Update version of udf-examples and pca-examples to 22.08.0-SNAPSHOT

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
UDF example jar refer to rapids branch-22.08
> UDF example jar refer to rapids branch-22.08

- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
> spark-rapids-ml version to 22.08.0-SNAPSHOT

- .github/workflows/auto-merge.yml
> Enable automerge from 22.08 to 22.10

- docs/get-started/xgboost-examples/notebook/python-notebook.md
- docs/get-started/xgboost-examples/notebook/toree.md
- docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
- docs/get-started/xgboost-examples/on-prem-cluster/standalone-python.md
- docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md
- docs/get-started/xgboost-examples/on-prem-cluster/yarn-python.md
- docs/get-started/xgboost-examples/on-prem-cluster/yarn-scala.md
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-ETL.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-gpu.ipynb
Signed-off-by: Suraj Aralihalli <suraj.ara16@gmail.com>
> Fix deprecated parameter spark.rapids.memory.gpu.pooling.enabled and other bugs in readme

- docs/get-started/xgboost-examples/notebook/python-notebook.md
- docs/get-started/xgboost-examples/notebook/toree.md
- docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
- docs/get-started/xgboost-examples/on-prem-cluster/standalone-python.md
- docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md
- docs/get-started/xgboost-examples/on-prem-cluster/yarn-python.md
- docs/get-started/xgboost-examples/on-prem-cluster/yarn-scala.md
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-ETL.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-gpu.ipynb
auto-merge triggered by github actions on `branch-22.08` to create a PR keeping `branch-22.10` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-22.08 to branch-22.10 [skip ci] [bot]

- docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md
Signed-off-by: Suraj Aralihalli <suraj.ara16@gmail.com>
> fix bug GPUMain -> Main

- examples/UDF-Examples/Spark-cuSpatial/gpu-run.sh
- examples/UDF-Examples/Spark-cuSpatial/notebooks/cuspatial_sample_standalone.ipynb
Update cuspatial Dataset and jars path for automatic tests
> Update Dataset and jars path for automatic tests

- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
> fix notebook display issue

- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
- examples/UDF-Examples/Spark-cuSpatial/README.md
- examples/UDF-Examples/Spark-cuSpatial/gpu-run.sh
- examples/UDF-Examples/Spark-cuSpatial/notebooks/cuspatial_sample_standalone.ipynb
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-ETL.ipynb
as title. Verified 22.10 examples build in internal pipeline
> Init 22.10.0-SNAPSHOT

- examples/XGBoost-Examples/README.md
add more details/notes for the mortgage perforamcne tests
> add more details/notes for the mortgage perforamcne tests

- .github/workflows/auto-merge.yml
as title. https://github.com/NVIDIA/spark-rapids-examples/tree/branch-22.12 is created
> Enable automerge from 22.10 to 22.12 

- examples/ML+DL-Examples/Spark-cuML/pca/Dockerfile
- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
- examples/UDF-Examples/Spark-cuSpatial/Dockerfile
- examples/UDF-Examples/Spark-cuSpatial/Dockerfile.awsdb
- examples/UDF-Examples/Spark-cuSpatial/README.md
- examples/UDF-Examples/Spark-cuSpatial/gpu-run.sh
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
- examples/UDF-Examples/Spark-cuSpatial/src/main/native/CMakeLists.txt
- examples/UDF-Examples/Spark-cuSpatial/src/main/native/src/PointInPolygonJni.cpp
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
this pr is to fix #238 
Some UDF calls cudf API, dev branch needs to target the latest snapshot codes(rapids/cudf) so that the CICD jobs could catch the issue(API changes) in time.
> target dev codes to latest snapshot

- .github/workflows/auto-merge.yml
Automerge from branch-22.12 to branch-23.02
> Enable automerge 22.12 to 23.02

- examples/XGBoost-Examples/agaricus/python/com/nvidia/spark/examples/agaricus/main.py
To fix https://github.com/NVIDIA/spark-rapids-examples/issues/255
> [xgboost] fix agaricus path checking issue

- examples/XGBoost-Examples/agaricus/python/com/nvidia/spark/examples/agaricus/main.py
auto-merge triggered by github actions on `branch-22.12` to create a PR keeping `branch-23.02` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-22.12 to branch-23.02 [skip ci] [bot]

- docs/get-started/xgboost-examples/csp/databricks/generate-init-script-10.4.ipynb
- docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
- docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
- examples/ML+DL-Examples/Spark-cuML/pca/README.md
- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
- examples/UDF-Examples/Spark-cuSpatial/gpu-run.sh
- examples/UDF-Examples/Spark-cuSpatial/notebooks/cuspatial_sample_standalone.ipynb
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/python/cv-mortgage-gpu.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-ETL.ipynb
- examples/XGBoost-Examples/taxi/notebooks/python/taxi-ETL.ipynb
- examples/XGBoost-Examples/taxi/notebooks/scala/taxi-ETL.ipynb
update versions to v23.02-snapshot for CICD jobs
> update versions to v23.02-snapshot for CICD jobs

- .github/workflows/auto-merge.yml
> Enable auto-merge 23.02 to 23.04

- examples/ML+DL-Examples/Spark-cuML/pca/Dockerfile
- examples/ML+DL-Examples/Spark-cuML/pca/README.md
- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
- examples/UDF-Examples/Spark-cuSpatial/gpu-run.sh
- examples/UDF-Examples/Spark-cuSpatial/notebooks/cuspatial_sample_standalone.ipynb
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
- examples/UDF-Examples/Spark-cuSpatial/src/main/native/CMakeLists.txt
- examples/XGBoost-Examples/mortgage/notebooks/python/cv-mortgage-gpu.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-ETL.ipynb
- examples/XGBoost-Examples/taxi/notebooks/python/taxi-ETL.ipynb
- examples/XGBoost-Examples/taxi/notebooks/scala/taxi-ETL.ipynb
update the dependency version to v23.04
> update the dependency version to v23.04

- .github/workflows/auto-merge.yml
> enable automerge from 2304 to 2306 [skip ci]

- examples/XGBoost-Examples/utility/scala/src/com/nvidia/spark/examples/utility/XGBoostArgs.scala
To fix https://github.com/dmlc/xgboost/issues/9145
> Change the rabit tracker config accordingly

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
fix UDF native build issue according https://github.com/rapidsai/cudf/pull/13117
> fix Cmake build issue v2306

- examples/XGBoost-Examples/pom.xml
cherry-picked from https://github.com/NVIDIA/spark-rapids-examples/pull/292
> update xgb dep to the latest

- examples/XGBoost-Examples/pom.xml
auto-merge triggered by github actions on `branch-23.04` to create a PR keeping `branch-23.06` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-23.04 to branch-23.06 [skip ci] [bot]

- examples/ML+DL-Examples/Spark-cuML/pca/Dockerfile
- examples/ML+DL-Examples/Spark-cuML/pca/README.md
- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
- examples/UDF-Examples/Spark-cuSpatial/gpu-run.sh
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
update versions to v23.08-snapshot for CICD jobs
> update versions to v23.08-snapshot for CICD jobs

- examples/MIG-Support/device-plugins/gpu-mig/pom.xml
- examples/XGBoost-Examples/pom.xml
This pr is to cherry-pick some changes from #308 to address Nspect CVE issues on the old dev branch(2306).
> address CVE issues

- examples/MIG-Support/device-plugins/gpu-mig/pom.xml
- examples/XGBoost-Examples/pom.xml
auto-merge triggered by github actions on `branch-23.06` to create a PR keeping `branch-23.08` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-23.06 to branch-23.08 [skip ci] [bot]

- .github/workflows/auto-merge.yml
Auto merge to branch-23.10 from branch-23.08
> Auto merge to branch-23.10 from branch-23.08 [skip ci]

- examples/ML+DL-Examples/Spark-cuML/pca/Dockerfile
- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
This pr is to update the UDF and Plugin dependency from 2308 to 2310 for testing
> update the udf and plugin dependency from 2308 to 2310

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
update versions to v23.12-snapshot for CICD jobs
> update udf version for cicd failure

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
auto-merge triggered by github actions on `branch-23.12` to create a PR keeping `branch-24.02` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-23.12 to branch-24.02 [skip ci] [bot]

- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/UDF-Examples/RAPIDS-accelerated-UDFs/pom.xml
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
update version to 2402 for CICD
> update version to 2402 for CICD

- .github/workflows/auto-merge.yml
Target to branch-24.02
Enable auto-merge CI
Signed-off-by: Tim Liu [timl@nvidia.com](mailto:timl@nvidia.com)
> Enable auto-merge from branch-24.02 to branch-24.04 [skip ci]

- examples/XGBoost-Examples/agaricus/pom.xml
- examples/XGBoost-Examples/aggregator/pom.xml
- examples/XGBoost-Examples/assembly/assembly-no-scala.xml
- examples/XGBoost-Examples/mortgage/pom.xml
- examples/XGBoost-Examples/pom.xml
- examples/XGBoost-Examples/taxi/pom.xml
- examples/XGBoost-Examples/utility/pom.xml
auto-merge triggered by github actions on `branch-24.02` to create a PR keeping `branch-24.04` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-24.02 to branch-24.04 [skip ci] [bot]

- .github/workflows/auto-merge.yml
> Auto merge PRs to branch-24.06 from branch-24.04 [skip ci]

- .github/workflows/auto-merge.yml
- .github/workflows/signoff-check.yml
update actions version for Node.js 20
> update actions version

- examples/XGBoost-Examples/pom.xml
- examples/XGBoost-Examples/utility/scala/src/com/nvidia/spark/examples/utility/XGBoostArgs.scala
XGBoost PR https://github.com/dmlc/xgboost/pull/10112 has changed the TrackerConf API, so make this PR to fix it.
> [xgboost] Fix tracker conf bug

- .github/workflows/add-to-project.yml
Add Github Action: Add new issues and pull requests to project
We need to add `secrets.PROJECT_TOKEN` to make the action run correctly
> Add GitHub action: add to project

- tools/databricks/[RAPIDS Accelerator for Apache Spark] Profiling Tool Notebook Template.ipynb
- tools/databricks/[RAPIDS Accelerator for Apache Spark] Qualification Tool Notebook Template.ipynb
**Changes**
- Add a note in tools Databricks notebooks about s3 event log support
> Update tools Databricks notebooks notes about s3 event log support

- examples/ML+DL-Examples/Spark-cuML/pca/README.md
- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
fix some version issue since PCA demo and cuSpecial demo only compatible with specific spark-rapids version
> fix compatible version issue

- examples/ML+DL-Examples/Spark-cuML/pca/README.md
- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
> Fix auto merge conflict 399

- examples/ML+DL-Examples/Spark-cuML/pca/README.md
- examples/ML+DL-Examples/Spark-cuML/pca/pom.xml
- examples/ML+DL-Examples/Spark-cuML/pca/spark-submit.sh
- examples/UDF-Examples/Spark-cuSpatial/pom.xml
auto-merge triggered by github actions on `branch-24.06` to create a PR keeping `branch-24.08` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-24.06 to branch-24.08 [skip ci] [bot]

- .github/workflows/auto-merge.yml
- tools/databricks/README.md
- tools/databricks/[RAPIDS Accelerator for Apache Spark] Profiling Tool Notebook Template.ipynb
- tools/databricks/[RAPIDS Accelerator for Apache Spark] Qualification Tool Notebook Template.ipynb
auto-merge triggered by github actions on `branch-24.08` to create a PR keeping `branch-24.10` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-24.08 to branch-24.10 [skip ci] [bot]

- examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/conditional_generation_tf.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/conditional_generation_torch.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/pipelines_tf.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/pipelines_torch.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/huggingface/sentence_transformers_torch.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/pytorch/image_classification_torch.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/pytorch/regression_torch.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/feature_columns_tf.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/image_classification_tf.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/keras-metadata_tf.ipynb
- examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/text_classification_tf.ipynb
auto-merge triggered by github actions on `branch-24.10` to create a PR keeping `branch-24.12` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-24.10 to branch-24.12 [skip ci] [bot]

- examples/SQL+DF-Examples/tpcds/README.md
Fix the colab link messed up in rebase
> Update "Open in Colab" link

- tools/emr/README.md
- tools/emr/[RAPIDS Accelerator for Apache Spark] Profiling Tool Notebook Template.ipynb
- tools/emr/[RAPIDS Accelerator for Apache Spark] Qualification Tool Notebook Template.ipynb
Fixes #458.
This PR adds Qualification and Profiling Notebooks for EMR platform. 
1. Ensure that you have an **EMR cluster** running.
2. Set up **EMR Studio** and **Workspace** by following the instructions in the [AWS Documentation](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-studio-create-studio.html):
- Select **Custom Settings** while creating the Studio.
- Choose the **VPC** and **Subnet** where the EMR cluster is running.
3. Attach the Workspace to the running EMR cluster. For more details, refer to the [AWS Documentation](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-studio-create-use-clusters.html).
1. Import the notebook into the EMR Workspace by dragging and dropping the notebook file.
2. In the **User Input** section of the notebook, enter the path …
> Include Tools Notebook for EMR

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
port the arg update from https://github.com/NVIDIA/spark-rapids-jni/pull/2583
> Prepare the arg to disable kvikIO remote IO

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
remove this after https://github.com/rapidsai/cudf/pull/17291 is merged
> Remove KvikIO workaround [skip ci]

- tools/databricks/README.md
- tools/emr/README.md
This PR updates title in README for EMR and Databricks Tools Notebooks
> Update title in README for EMR and Databricks Tools Notebooks

- tools/databricks/README.md
- tools/emr/README.md
This PR cherry picks changes in #469 in `branch-24.12` for re:invent purpose.
> Cherry-Pick: Updated title in README for EMR and Databricks Tools Notebooks (#469)

- examples/ML+DL-Examples/Spark-DL/dl_inference/README.md
- examples/ML+DL-Examples/Spark-DL/dl_inference/databricks/setup/init_spark_dl.sh
- examples/ML+DL-Examples/Spark-DL/dl_inference/dataproc/setup/start_cluster.sh
- examples/ML+DL-Examples/Spark-DL/dl_inference/requirements.txt
- examples/ML+DL-Examples/Spark-DL/dl_inference/torch_requirements.txt
auto-merge triggered by github actions on `branch-25.02` to create a PR keeping `branch-25.04` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-25.02 to branch-25.04 [skip ci] [bot]

- examples/ML+DL-Examples/Spark-DL/dl_inference/tensorflow/keras_resnet50_tf.ipynb
> Fix function typo

- docs/get-started/xgboost-examples/csp/dataproc/gcp.md
> Fix auto merge conflict 523

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
fix versions due to internal tool bug for example repo
> Update UDF example cmake version 25.04

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
auto-merge triggered by github actions on `branch-25.04` to create a PR keeping `branch-25.06` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-25.04 to branch-25.06 [skip ci] [bot]

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
fix versions due to internal tool bug for example repo
> Update UDF example cmake version 25.06

- examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt
> Main release2504 2

- examples/ML+DL-Examples/Spark-DL/dl_inference/databricks/setup/init_spark_dl.sh
- examples/ML+DL-Examples/Spark-DL/dl_inference/dataproc/setup/start_cluster.sh
Discovered conflicts between latest vLLM updates and existing libraries on CSP environments.
Pinning to 0.8.2 (which is confirmed to work) as a workaround pending a fix.
> Pin vLLM version for CSPs

- examples/XGBoost-Examples/agaricus/notebooks/python/agaricus-gpu.ipynb
- examples/XGBoost-Examples/agaricus/notebooks/scala/agaricus-gpu.ipynb
- examples/XGBoost-Examples/app-parameters/supported_xgboost_parameters_python.md
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/python/cv-mortgage-gpu.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/python/mortgage-gpu.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-gpu.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage_gpu_crossvalidation.ipynb
- examples/XGBoost-Examples/pom.xml
- examples/XGBoost-Examples/taxi/notebooks/python/cv-taxi-gpu.ipynb
- examples/XGBoost-Examples/taxi/notebooks/python/taxi-gpu.ipynb
- examples/XGBoost-Examples/taxi/notebooks/scala/taxi-gpu.ipynb
- examples/XGBoost-Examples/taxi/notebooks/scala/taxi_gpu_crossvalidation.ipynb
To fix https://github.com/NVIDIA/spark-rapids-examples/issues/551
> Fix tree_method

- examples/XGBoost-Examples/agaricus/notebooks/python/agaricus-gpu.ipynb
- examples/XGBoost-Examples/agaricus/notebooks/scala/agaricus-gpu.ipynb
- examples/XGBoost-Examples/app-parameters/supported_xgboost_parameters_python.md
- examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/python/cv-mortgage-gpu.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/python/mortgage-gpu.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-gpu.ipynb
- examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage_gpu_crossvalidation.ipynb
- examples/XGBoost-Examples/pom.xml
- examples/XGBoost-Examples/taxi/notebooks/python/cv-taxi-gpu.ipynb
- examples/XGBoost-Examples/taxi/notebooks/python/taxi-gpu.ipynb
- examples/XGBoost-Examples/taxi/notebooks/scala/taxi-gpu.ipynb
- examples/XGBoost-Examples/taxi/notebooks/scala/taxi_gpu_crossvalidation.ipynb
auto-merge triggered by github actions on `branch-25.08` to create a PR keeping `branch-25.10` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.
> [auto-merge] branch-25.08 to branch-25.10 [skip ci] [bot]

- docs/get-started/xgboost-examples/on-prem-cluster/standalone-python.md
> [DOC] Fix deadlink2510
